swapi:
  base-url: https://swapi.dev/api/

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

redis:
  enabled: true

springdoc:
  api-docs:
    path: /api/docs